name: Ruby

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, "3.0", head]
        include:
          - ruby: truffleruby-head
            needs: "test (2.5)" # It takes a long time to run this test, so let's run it after a passing 2.5
    env:
      RAILS_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # bundle installs and caches dependencies
    - name: Run tests
      run: bundle exec rake --trace
